services:
  - type: web
    name: graphviz-api
    env: python
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0